package Update.JsonClasses;

public class Rates {
    String USD,AED,ARS,BGN,BRL,BSD,CAD,CHF,CLP,CNY,COP,CZK,DKK,DOP,EGP,EUR,FJD,GBP,GTQ,HKD,HRK,HUF,IDR,ILS,INR,
            ISK,JPY,KRW,KZT,MXN,MYR,NOK,NZD,PAB,PEN,PHP,PKR,PLN,PYG,RON,RUB,SAR,SEK,SGD,THB,TRY,TWD,UAH,UYU,ZAR;

}
